### ISSUE TITLE
Update fonts and colors

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/zinc.coop#1]
@Wimsy113  did some really great aesthetic design work earlier last year in [zinc.is](https://github.com/zinc-collective/zinc.is), which I completely failed to migrate into zinc.coop when I set up and consolidated onto this site.

I'd love to apply the color and typography choices to zinc.coop, and will do so when I get a chance; unless someone beats me to it.

**Comment by zspencer** [comment]
@Wimsy113 - Do you think the current www.zinc.coop color and type is good enough? If so, can you close this ticket or leave feedback for me?

**Comment by Wimsy113** [comment]
Yup it's dope! I like how robust the purple is! Screams Zinc Coop.
