### ISSUE TITLE
Beautify the website

### ISSUE THREAD

**Issue by KellyAH** [zinc-collective/zinc.coop#103]
**Site Theme**
- [x] Update entire website look/feel to a more modern look. https://github.com/zinc-collective/www.zinc.coop/pull/105

**Homepage**
- [x] Update Home page (https://www.zinc.coop/) text to be easier to understand.  https://github.com/zinc-collective/www.zinc.coop/pull/112

**Products and Services page**
- [x] Clean up & Beautify Products and Services page https://github.com/zinc-collective/www.zinc.coop/pull/101

**About Us page**
- [x] Rename confusing Main nav menus https://github.com/zinc-collective/www.zinc.coop/pull/102
- [x] Update directory, filenames, references, to match the Renamed Main nav menus https://github.com/zinc-collective/www.zinc.coop/pull/114
- [x] Clean up & Beautify the People Page https://github.com/zinc-collective/www.zinc.coop/pull/102

**Join Us Section**
- [x] move the Code of Conduct and Operating Agreement to footer links https://github.com/zinc-collective/www.zinc.coop/pull/109
- [x] remove the Project Guidelines and Become a Maintainer bits. https://github.com/zinc-collective/www.zinc.coop/pull/110
- [x] consolidate all sub menu pages into 1 page with two sections and https://github.com/zinc-collective/www.zinc.coop/issues/103#issuecomment-1586255254 and remove Join Us sub menu https://github.com/zinc-collective/www.zinc.coop/pull/111
- [x] add redirects so URLs to removed pages do not 404 https://github.com/zinc-collective/www.zinc.coop/pull/113

**Updates Page**
- [x] Add https://opencollective.com/zinc-community/updates link https://github.com/zinc-collective/www.zinc.coop/pull/104
- [x] Add redirects so URLs to removed pages do not 404 https://github.com/zinc-collective/www.zinc.coop/pull/107#issuecomment-1586542450
- [x] Combine  financial-overview and meeting-notes pages into 1 page to remove sub menu  https://github.com/zinc-collective/www.zinc.coop/pull/107

**Contact page**
- [x] Fix Contact form https://github.com/zinc-collective/www.zinc.coop/pull/100
- [x] remove Contact Us page https://github.com/zinc-collective/www.zinc.coop/pull/105

**More work**
https://github.com/zinc-collective/www.zinc.coop/issues/103#issuecomment-1593369657

- [x] See how it looks to remove the background colors and borders on the header links https://github.com/zinc-collective/www.zinc.coop/pull/117
- [x] Change :hover color - lighten or darken on hover, rather than... become blue https://github.com/zinc-collective/www.zinc.coop/pull/116
  - [x] Change :hover color to a color that is WCAG compliance https://github.com/zinc-collective/www.zinc.coop/pull/118
- [x] Edit "Services" - to only have: 
a. Hosting a Space on Convene
b. Hosting a Convene Neighborhood
https://github.com/zinc-collective/www.zinc.coop/pull/115

**Comment by KellyAH** [comment]
CC: @zspencer , @anaulin Please review the list in the Description ☝️ and add more improvements you want me to make. This is a great project for me to practice frontend work (HTML,CSS,Tailwind, Eleventy, etc.) ❤️

**Comment by anaulin** [comment]
That list looks fine to me, @KellyAH !

If you move to the site to a preset "theme", it might make sense to remove the custom CSS in `default.css`, to make sure it doesn't interfere with whatever CSS is brought in by the theme.

Also note that the current main goal of the site is to (1) give a sense of what/who we are; (2) give a way to reach us, and (3) not be too embarrassing, so don't feel like you have to fix _all_ the things!

**Comment by zspencer** [comment]
I agree that this looks like a fine set of priorities. Removing cruft / interface elements is a great way to reduce embaressment even if you don't find a theme you like from eleventy.

One advantage to writing your own theme is now you've written a theme once; which is quite the useful skill in the world of freelance or agency website development. That may not be sufficient however.

From my perspective; I would love to move the www site into Convene and set up Furniture to replicate the parts of the site that are actually helpful/interesting/important. But I think that's far outside the scope of this particular issue.

**Comment by KellyAH** [comment]
consolidating all the "Join Us" submenu pages into 1 page is going to be tough by myself. @anaulin and @zspencer do ya'll have any preferences/suggestions/recommendations?

<img width="279" alt="Screenshot 2023-06-09 at 8 52 55 PM" src="https://github.com/zinc-collective/www.zinc.coop/assets/16140873/af1d0d53-3d15-479f-8878-bab27dad03d4">

**Comment by zspencer** [comment]
I think I would move the Code of Conduct and Operating Agreement to footer links and ditch the Project Guidelines and Become a Maintainer bits.

Then I would make the Join Us a single page with two sections:

1. Become a Co-Conspirator in our Group Chat (link to the Discord)
2. Become a Sponsor in our Open Collective
3. Become a Contributor on Convene or Moment Park (each link to the CONTRIBUTING.md in the repo)

**Comment by zspencer** [comment]
A few things that would help me feel less embaressed to share the site:

1. The background colors and borders on the header links seem a bit much. What would it look like without them?
2. That :hover color is ... not ideal. Could we either lighten or darken on hover, rather than... become blue?
3. I would rather we did not offer "Services" at all at this time, beyond:
  a. Hosting a Space on Convene 
  b. Hosting a Convene Neighborhood

**Comment by KellyAH** [comment]
> 2. That :hover color is ... not ideal. Could we either lighten or darken on hover, rather than... become blue?
> 3. I would rather we did not offer "Services" at all at this time, beyond:
>   a. Hosting a Space on Convene
>   b. Hosting a Convene Neighborhood

@zspencer 
2. Do you want the :hover color to be a lighter or darker gradation of the link color `'zinc-pastel-pink': '#FE9BFF'`, or `'zinc-hot-pink': '#F43EF3'`, or a totally different color?

3. Do you want me to replace the Services list:
<img width="766" alt="Screenshot 2023-06-15 at 1 27 36 PM" src="https://github.com/zinc-collective/www.zinc.coop/assets/16140873/0c801ba7-706d-49a0-81de-eb3248f50d89">

with this?: 
```
* Hosting a Space on Convene
* Hosting a Convene Neighborhood
```

And make those links to  specific URLs? Which URLs?

**Comment by zspencer** [comment]
Re: Link color - I think either darker or lighter from the current link color will be fine; the blue is just incredibly jarring.

Re: Services - Maybe just one link to https://convene.zinc.coop?

**Comment by KellyAH** [comment]
> The background colors and borders on the header links seem a bit much. What would it look like without them?

@zspencer It kinda looks minimalist/modern? Do you like it/think it looks better or worse? 

![rmv bkgd color and borders](https://github.com/zinc-collective/www.zinc.coop/assets/16140873/bccd7169-a256-4e4f-86cf-3da66d50ea08)

<img width="773" alt="Screenshot 2023-06-15 at 9 12 24 PM" src="https://github.com/zinc-collective/www.zinc.coop/assets/16140873/24304961-d7c0-47b7-92f6-8b75a654a3a0">

**Comment by anaulin** [comment]
I like it without the borders a lot! In addition, I would:
* add a bit more spacing to the left of each icon (except the first one, the home icon), to more clearly separate each menu item
* remove the hover darker background color, and leave only a hover effect that lightens the text

**Comment by zspencer** [comment]
I agree with @anaulin ! This looks a lot nicer!
