### ISSUE TITLE
Add Ross to the "about us" page

### ISSUE THREAD

**Issue by anaulin** [zinc-collective/zinc.coop#125]
Add Ross to the "about us" page, here: https://www.zinc.coop/about-us/

Can be done by adding another entry into the `about-us/index.json` file: https://github.com/zinc-collective/www.zinc.coop/blob/cbb2399dd8dfb3fd07041270f2af9a88a2912ae2/src/about-us/index.json

**Comment by rosschapman** [comment]
✅ Done: https://github.com/zinc-collective/www.zinc.coop/pull/128
