### ISSUE TITLE
Apply TailwindUI to zinc.coop

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/zinc.coop#13]
To not have to hand roll our own common components, we acquired a team license for [TailwindUI](https://tailwindui.com/). The password lives in the shared password manager for zinc-coop full members; as they do not have user-level access controls yet (or possibly ever :)).

- [X] Create a sample landing page using TailwindUI to get a feel for how it looks
  - [ ] Create a Footer that looks nice for [https://www.zinc.coop/convene/](https://www.zinc.coop/convene)
- [ ] Create a Layout that leverages the same structure as the convene landing page and apply it on other pages.
  - [ ] Home
  - [ ] Products and Services
  - [ ] Operating Agreement
  - [ ] Join Us
  - [ ] About Us
    - [ ] Financial Overview
    - [ ] Meeting Notes
  - [ ] Contact Us

**Comment by user512** [comment]
Tailwind UI is applied in `/convene` and the site looks better now.

**Comment by zspencer** [comment]
We may want to make a set of check-boxes for making the rest of the website look like the convene landing page before closing this, as there's still work to be done.

**Comment by anaulin** [comment]
I'd like to start inching this forward (aligns with a personal urge that I've had lately at getting better at CSSing), but I need first clarity on what is agreed upon path.

There is a checkbox in the issue description that talks about creating a layout that uses the "convene landing page structure", to apply it to the rest of the website. I'm wondering if that's accurate still, because the Convene landing page at https://www.zinc.coop/convene/ seems to have a very different structure than what I see in the mocks.

Is the rough structure in https://xd.adobe.com/view/03a08823-a25a-489c-8213-5a417b41fe4f-56f3/screen/4213fae9-d9ef-4784-a622-64b8117d2549 the way I should be moving this in? (i.e. menu bar at the top, slightly modified darker purple background, black footer)?

@colombene @user512 @zspencer

**Comment by user512** [comment]
I think @colombene or @zspencer might have a better idea since I am not aware of this Zinc website mock. But it looks nice!

**Comment by zspencer** [comment]
Previously, I was hoping we could leverage TailwindUI to give us pre-built components that play nicely across operator contexts (small device, walking around; middle-sized device sitting down; large device sitting down) but I'm down with following @colombene's mocks.

Ultimately, my hope is that our website is a reflection of _us_; and while TailwindUI's aesthetic lands nicely in my personal aesthetic preferences; I would rather we embraced our design teams aesthetic taste than my own :).

My _deepest_ concern is for [visual hierarchy](https://www.nngroup.com/articles/principles-visual-design/), especially as it relates to typography; given that our website is a part of [the written web](https://www.nngroup.com/topic/writing-web/)..

**Comment by colombene** [comment]
This could map to Tailwind. Just FYI, these are primarily ideas or wireframes, not pixel-perfect, standardized, visually designed mocks. I also don't usually own front-end development or know how to implement libraries. So there's probably some bridging needed. Brand also is a bit in flux. It needs subsequent rounds to get more refined. Tailwind does not seem to be available for XD in a significant way so I often use other templates or just start entering in elements directly to get the ideas out quicker. But I can start porting Tailwind to XD. 

Beyond that, I'm hesitant to use it exactly. I think it might look like basic Silicon Valley style tech/marketing. Personally I think Zinc is better that that and more unique. But maybe that offers comfort, familiarity or legitimacy. Perhaps we can discuss - or I just need to better understand the parameters of customization with fonts, colors and graphic elements.

**Comment by anaulin** [comment]
A quick drive-by comment to clarify that I was thinking we would use Tailwind to implement something close to Colombene's mocks.

My comment about the Convene landing was just pointing out that this page has a very different layout (no menu bar on top, no Zinc logo in corner, no footer, etc), and so it seems a good first step here would be to start building a layout template that uses Tailwind to build the refreshed site.

I hope that makes sense. Sorry for rushed comment.

**Comment by colombene** [comment]
Oh yea, Convene was imagined as its own thing with its own landing and branding. However, it might be an obstacle if there isn't a dedicated designer. It might be easier to just tie to Zinc and refine one look for now.

**Comment by anaulin** [comment]
Doesn't feel like an obstacle for now, in the sense that the Convene landing is done for now and we can just leave it as it is while we work on the rest of the website. (And in the future we can tie the Convene landing into the rest of the site, or evolve it in its own way, or whatever.)

**Comment by zspencer** [comment]
It sounds like we're in alignment here re: Tailwind as a "skeleton" and Colombene's art style as "heart, flesh, and skin" :). 

The aesthetic pieces I like about Tailwind are the "spaciousness" between elements, the communicativeness and strong contrast of their background, interactive, and text elements in their color schemes, and the clear visual hierarchy that includes typography. The... sterility does not feel particularly good to me; however.

I _much prefer_ the fertile textures and mood of @colombene's work, and I'm super excited to see how we combine type with texture in a way that holds true to Colombene's art while maintaining glanceability and scannability for the written content. 

Re: the alternative layouts - I was working from the position that each "Product" landing page would place that product or service front and center; and provide "backlinks" to the rest of Zinc in the footer; this way we can drop people on targeted landing pages with calls-to-action that are appropriate for the given target audience in the appropriately prominent places. For example, the Convene landing page may want a "Become a Resident!" or "Claim your Space!" call to action that sits in the header at an appropriate location that supercedes what would live in the header for the more "explore and understand zinc" pages.

That said, this is probably much less useful now that convene.zinc.coop exists as it's own site; and discarding that intent will make www much easier to work with.

**Comment by anaulin** [comment]
I didn't know about convene.zinc.coop, that's helpful to know about (although going there, right now it is serving me a default Rails error page).

Agreed that we seem in alignment: let's use Tailwind to move toward's Colombene's designs, deal with Convene if/when later and separately.

**Comment by user512** [comment]
[convene.zinc.coop](https://convene.zinc.coop/) is Convene.
Convene root path doesn't route to anything and that's why you see a Rails not found page.
