### ISSUE TITLE
Automate the process of receiving and cataloging contributor agreements

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/zinc.coop#17]
Because we mandate that contributors assign copyright to Zinc Collective, and that can be a speedbump that knocks some enthusiasm out of contributors, it may be nice to have an automated process for collecting and recording contributor agreements. 

@drllau [mentioned one option while working in Compensated](https://github.com/zinc-collective/compensated/pull/58#issuecomment-609516106), [CLAHub](https://github.com/clahub/clahub).

@maximegalon5 - is this something you think is worth doing? At present, our process for getting contributors, pending members and members onboarded falls pretty heavily on your shoulders; and if it would free you up to have more thought for the higher-level stuff it may be worth rallying some of  the folks in @zinc-collective/core to figure out a pathway forward.

I, personally, do not believe this is particularly urgent; but if you do then I'd be down to brainstorm some ways to do it that are light weight.

**Comment by drllau** [comment]
Well, since it borders on legal aspects, I'm willing to put up my hand to pilot a trial on my own repos before deploying it for Zinc just to see the workflow impact. I just can't work on it until post-Easter as mentoring for Global Hackathon.

**Comment by zspencer** [comment]
That would be awesome! I'd be down to participate in testing. No rush on our end whatsoever.
