### ISSUE TITLE
Maintainer may create a new project from a guide or template

### ISSUE THREAD

**Issue by user512** [zinc-collective/zinc.coop#28]
In order to more easily decompose projects into smaller components and bring new ideas to the table
As a Maintainer
I would like a "Create a Project" guide or GitHub Project Template

**Comment by zspencer** [comment]
I accidentally did a WIP commit to the development branch of our template.. but otherwise, @user512, is this kind of what you're looking for? 

https://github.com/zinc-collective/new-project-template/commit/64468df22c9d3bcee97f2725809ba3196b02504b

**Comment by zspencer** [comment]
@user512 - As a mainainer, do you think the landing page at https://www.zinc.coop/maintaining/ meets your needs for now? And if so, would you feel comfortable closing this ticket now that it's merged and in production?

**Comment by zspencer** [comment]
Closing due to lack of response, assuming current maintainer guide is good enough for now :).

**Comment by user512** [comment]
I think this is good enough.
