### ISSUE TITLE
New Contributors assign rights to ZC without manual intervention

### ISSUE THREAD

**Issue by maximegalon5** [zinc-collective/zinc.coop#32]
See https://soloish.slack.com/archives/GT5UFAHQC/p1588618455046100 for reference.

The idea is that anyone can sign and send to ZC 

see https://docs.google.com/document/d/17AJSmABWD_BJnsjS4Ihw9urC88yu9IYW2eWFKLOEHt0/edit for the template

```features/contributing.feature
Scenario: Contributor assign rights to ZC without manual intervention
  Given a Contributor who has not yet signed a Contributor License Agreement
  When the Contributor submits a Contribution
  Then they are instructed to eSign a Contributor License Agreement
```

Thought: Is this even required?

**Comment by zspencer** [comment]
Re: Is this required - I don't know; I think that Contributor License Agreements are somewhat controversial; but they _do_ make it clear that contributors grant unlimited rights to us. 

Jitsi, for instance, has a requirement that folks who submit a patch must [sign a contributor license agreement](https://github.com/jitsi/jitsi/blob/master/CONTRIBUTING.md#contributor-license-agreement) which I think makes a lot of sense.

An example of this flow is here: https://github.com/jitsi/jitsi-meet/pull/6627#issuecomment-626087568, where I submitted a patch to jitsi-meet, they directed me to the ICLA and CCLA template in DocuSign, and I filled it out.

It required no manual intervention on their operations team part, and was a pretty short and to-the-point CLA.

If you're willing to investigate how we could use off-the-shelf tooling for the eSign bit, I'd be down to automate prompting new contributors and updating our contributing guide to include the links to the eSign page.
