### ISSUE TITLE
Developer can find sitemap

### ISSUE THREAD

**Issue by colombene** [zinc-collective/zinc.coop#44]
I posted this to Figma (shown on a call a few days ago): https://www.figma.com/file/CohXLEIN3RXd0Zc8buIV8A/Zinc?node-id=0%3A756

**Comment by maximegalon5** [comment]
This is great! Thank you :)

**Comment by zspencer** [comment]
I've dropped a couple comments to clarify some things about where particular projects are; and overall I really like that we actually have a "plan" for the information architecture of the site instead of me just poking stuff when I think about it.

**Comment by colombene** [comment]
Thanks for adding. Wasn't sure what to do with it in GitHub but looks like I can add to README in the future.

**Comment by zspencer** [comment]
Take your time :). It's a big tool; They have a [massive guide](https://help.github.com/en/github) with a few parts that could be useful to you:

1. [Writing on Github](https://help.github.com/en/github/writing-on-github) which is probably a bit too basic for you
2. [Managing your Work on Github](https://help.github.com/en/github/managing-your-work-on-github)
3. [Managing Files on Github](https://help.github.com/en/github/managing-files-in-a-repository/managing-files-on-github) which has more of the file-system level operations.

And, for bonus points so you can hold me accountable when I fuck things up; the section on [building a strong community](https://help.github.com/en/github/building-a-strong-community) is a good read.
