### ISSUE TITLE
Add "Work: services" and "People" pages to website

### ISSUE THREAD

**Issue by anaulin** [zinc-collective/zinc.coop#71]
Implement the initial version of the "people" and "work" pages in the Zinc website mocks. These are comps #11 and #5 in  https://xd.adobe.com/view/03a08823-a25a-489c-8213-5a417b41fe4f-56f3/grid (also crappily screen-capped for easy direct reference in this ticket).

The focus of this ticket is on the content, and less on the look & feel (in particular, note that the mocks below have different link colors; it is out of the scope of the work in this issue to reconcile those, and instead we'll use the stylesheet that is currently on the site).

- [x] Clarify where in the menu bar are these pages linked from
- [x] Finalize content/wording for "Work: Services" page, available for comment [here](https://docs.google.com/document/d/17DjiqnA5ItNQPi_Qj8NfLPgFjZba2lDZyvGq-HGjGCw/edit#heading=h.hpu7eo6q3siw)
- [x] Collect links and bios of members that want to initially be listed there
  - [ ] @colombene 
  - [x] @zspencer 
  - [x] @anaulin 
  - [x] [add yourself here if you want]
- [ ] Implement "Work: Services" page
- [x] Implement "People" page

![Screen Shot 2021-01-28 at 9 43 05 AM](https://user-images.githubusercontent.com/6729309/106177770-c5922f00-614d-11eb-86d4-88095d1fe625.png)
![Screen Shot 2021-01-28 at 9 42 49 AM](https://user-images.githubusercontent.com/6729309/106177777-c6c35c00-614d-11eb-8ff2-32ea0f00278f.png)

**Comment by anaulin** [comment]
Right now the website has one big "Product and Services" menu item, which links directly to a page that lists our products (https://www.zinc.coop/product-and-services/). One way I see to iterate on this towards our ultimate vision is renaming that top menu item to "Work", and having it contain a sub-menu with "Products" and "Services".

The site and menu structure would change as follows:
* Before: "Products and Services", with the content at https://www.zinc.coop/product-and-services/
* After:
  * "Work" (top-level menu, doesn't link to anything, if you hover / click, it shows sub-menu)
    * "Products" (content that is current at https://www.zinc.coop/product-and-services/)
    * "Services": new content from the mock above (to be workshopped)

@colombene does this make sense to you? or did you envision something else?

For the "People" page, the mocks show that as being its own top-level menu item, which I like philosophically (we are people-centric!), so I'll plan to add this to the menu bar as a top item.

**Comment by colombene** [comment]
This is great to see! :)
I went back and forth on services because couldn't get a sense if the team wanted it. I'd love it, but maybe we should do a check-in first and confirm contact info. The latest live mobile mock-ups don't have it but it can be like you say. Or could be side by side in desktop and stack in mobile. I will also update the copy doc rn to match the latest XD comps: https://docs.google.com/document/d/17DjiqnA5ItNQPi_Qj8NfLPgFjZba2lDZyvGq-HGjGCw/edit?usp=sharing

**Comment by zspencer** [comment]
I'm in favor of a "Professional Services Network" approach 🎉 🎉 🎉  towards getting contributors and maintainers faces in front of the world in support of elevating their career, whether that's freelancing while working on side-projects or working full-time and leveraging Zinc to further develop their skills.
