### ISSUE TITLE
Fix the contact form

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/zinc.coop#90]
https://www.zinc.coop/contact-us/ doesn't work, because we let the wegotyourback.today project go away.

Probably should either:

1. Create an Airtable form with name, email, and message (so we don't have to expose our email on a public site)
2. Replace it with links to our twitter and the members@zinc.coop email address? https://github.com/zinc-collective/www.zinc.coop/pull/100
3. Replace it with [Convene](https://github.com/zinc-collective/convene/issues/847)

2 is easier; 3 is cooler, 1 is also cool.

**Comment by anaulin** [comment]
@KellyAH I just verified that we have an address hello@zinc.coop which works and seems like a good fit for option #2 above.

I'd skip the Twitter part as well, given the intensifying en-muskification of the twitterverse. 💩

**Comment by KellyAH** [comment]
2. is done. We'll need to decide if the next step is 1. and/or 3.

**Comment by zspencer** [comment]
For now; I think we can safely consider this "done"; since visitors can now contact us directly. If we want to do something more; we can create a new issue to consider those steps. 

I would love to move the entire www.zinc.coop website into Convene; so that when we improve how our website works and looks for us; it improves how Spaces work for our clients. 

That said, keeping the site separate lets you fiddle more directly with plain-old-html-and-css; which is a much more digestible chunk on the learning side of things.

I'm hesitant to do the Airtable form just yet; but if we start getting obnoxious emails I will be persuaded otherwise. Thoughts @anaulin ?

**Comment by anaulin** [comment]
Let's call this done and move onto more valuable things. 🎉
